parameters:
  doctrine.orm.entity_dirs:
    - '%root_dir%/src/Entity'
    - '%root_dir%/plugin/AcmeProject/src/Entity'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
    bind:
      Psr\Log\LoggerInterface: '@Monolog\Logger'

  _instanceof:
    # apply tags to necessary services
    Devops\Resource\ProjectInterface:
      tags: ['devops.project']

  Acme\:
    resource: '../plugin/AcmeProject/src/*'
    exclude: '../plugin/AcmeProject/src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
  Acme\Entity\MyRelease:
    tags: ['devops.release']
