imports:
  - { resource: parameters.yaml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Devops\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  # Support functionality for assisting in output display preferences.
  Devops\Display\DateTimeZone:
    class: DateTimeZone
    arguments: ["%display.datetime.timezone%"]
  # Additional custom wiring for auto-wired objects.
  Devops\Command\ReleaseCreateCommand:
    calls:
      - [setDateTimeZone, ['@Devops\Display\DateTimeZone']]
      - [setDateTimeFormat, ['%display.datetime.format%']]
  Devops\Command\ReleaseListCommand:
    calls:
      - [setDateTimeZone, ['@Devops\Display\DateTimeZone']]
      - [setDateTimeFormat, ['%display.datetime.format%']]

  ### DOCTRINE
  Doctrine\ORM\Configuration:
    factory: [Doctrine\ORM\Tools\Setup, createAnnotationMetadataConfiguration]
    arguments:
      - ['%doctrine.orm.entity_dir%']
      - '%doctrine.orm.dev_mode%'
      - '%doctrine.orm.proxy_dir%'
      - ~
      - '%doctrine.orm.use_simple_annotation_reader%'
  Doctrine\ORM\EntityManager:
    factory: [Doctrine\ORM\EntityManager, create]
    arguments:
      - '%doctrine.orm.connection%'
      - '@Doctrine\ORM\Configuration'
  ### MONOLOG
  Monolog\Logger:
    arguments:
      - main
    calls:
      - [pushHandler, ['@Monolog\Handler\StreamHandler']]
      - [pushProcessor, ['@Monolog\Processor\UidProcessor']]
  Monolog\Handler\StreamHandler:
    arguments:
      - '%log_file_path%'
      - '%log_file_verbosity%'
  Monolog\Processor\UidProcessor: ~
  Psr\Log\LoggerInterface:
    alias: Monolog\Logger
