imports:
  - { resource: parameters.yaml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
    bind:
      $github_organization: '%github.organization%'
      # any service asking for a LoggerInterface will get Monolog
      Psr\Log\LoggerInterface: '@Monolog\Logger'

  Devops\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  _instanceof:
    # apply tags to necessary services
    Symfony\Component\Console\Command\Command:
      tags: ['console.command']
    Devops\Command\DateHelperInterface:
      calls:
        - [setDateTimeZone, ['@Devops\Display\DateTimeZone']]
        - [setDateTimeFormat, ['%display.datetime.format%']]

  # Support functionality for assisting in output display preferences.
  Devops\Display\DateTimeZone:
    class: DateTimeZone
    arguments: ['%display.datetime.timezone%']
  # Additional custom wiring for auto-wired objects.
  Devops\EventListener\ExitCodesListener:
    tags:
      - { name: console.event_listener, event: !php/const Symfony\Component\Console\ConsoleEvents::COMMAND, method: defineUserExitCodes }
  Devops\EventListener\LoggingListener:
    tags:
      - { name: console.event_listener, event: !php/const Symfony\Component\Console\ConsoleEvents::COMMAND,   method: logCommandName }
      - { name: console.event_listener, event: !php/const Symfony\Component\Console\ConsoleEvents::TERMINATE, method: logCommandStatus }

  ### DOCTRINE
  Doctrine\ORM\Configuration:
    factory: [Doctrine\ORM\Tools\Setup, createAnnotationMetadataConfiguration]
    arguments:
      - '%doctrine.orm.entity_dirs%'
      - '%doctrine.orm.dev_mode%'
      - '%doctrine.orm.proxy_dir%'
      - ~
      - '%doctrine.orm.use_simple_annotation_reader%'
  Doctrine\ORM\EntityManager:
    factory: [Doctrine\ORM\EntityManager, create]
    arguments:
      - '%doctrine.orm.connection%'
      - '@Doctrine\ORM\Configuration'
  ### MONOLOG
  Devops\Logger\ConsoleHandler:
    arguments:
      - '@Symfony\Component\Console\Output\ConsoleOutput'
    calls:
      - [setFormatter, [!service { class: Devops\Logger\Formatter\ConsoleLineFormatter,
                                   arguments: [~, ~, false, true] }]]
  Monolog\Logger:
    arguments:
      - main
    calls:
      - [pushHandler,   ['@Devops\Logger\ConsoleHandler']]
      - [pushHandler,   [!service { class: Monolog\Handler\StreamHandler,
                                    arguments: ['%log_file_path%', '%log_file_verbosity%'] }]]
      - [pushProcessor, [!service { class: Monolog\Processor\UidProcessor }]]
  ### GITHUB API
  Github\Client:
    calls:
      - [authenticate, ['%github.tokenOrLogin%', '%github.password%', '%github.authMethod%']]
  ### SYMFONY CONSOLE APPLICATION HELPERS
  Symfony\Component\Console\Output\ConsoleOutput: ~
